In [37]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')
df = pd.read_csv('/kaggle/input/datasets/muhammadwaqas023/ai-impact-in-future-on-jobs-market-in-2030/AI_Impact_on_Jobs_2030.csv')
df.head(2)

/kaggle/input/datasets/muhammadwaqas023/ai-impact-in-future-on-jobs-market-in-2030/AI_Impact_on_Jobs_2030.csv

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
0,AIJ-100000,Data Engineer,Healthcare,Japan,PhD,1,0.25,0.78,Yes,207392,"Python, Communication, Deep Learning",Low,3,37,Enterprise,High,2.08,Yes,3.86,Growing
1,AIJ-100001,Healthcare Analyst,Retail,UK,Bachelor,24,0.73,0.33,No,140785,"Deep Learning, Azure, Communication, TensorFlo...",Low,-5,42,Startup,Moderate,4.54,No,4.23,Growing

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.metrics import accuracy_score,confusion_matrix

In [39]:
df.shape

(3000, 20)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Employee_ID              3000 non-null   object
 1   Job_Title                3000 non-null   object
 2   Industry                 3000 non-null   object
 3   Country                  3000 non-null   object
 4   Education_Level          3000 non-null   object
 5   Years_Experience         3000 non-null   int64
 6   AI_Replacement_Risk      3000 non-null   float64
 7   Future_Demand_Score      3000 non-null   float64
 8   Remote_Work_Possibility  3000 non-null   object
 9   Average_Salary_USD       3000 non-null   int64
 10  Required_Skills          3000 non-null   object
 11  Automation_Level         3000 non-null   object
 12  Job_Growth_2030          3000 non-null   int64
 13  Work_Hours_Per_Week      3000 non-null   int64
 14  Company_Size             3000 non-null   object
 15  AI_Tool_Usage            3000 non-null   object
 16  Performance_Score        3000 non-null   float64
 17  Upskilling_Needed        3000 non-null   object
 18  Job_Satisfaction         3000 non-null   float64
 19  Hiring_Trend_2026        3000 non-null   object
dtypes: float64(4), int64(4), object(12)
memory usage: 468.9+ KB

In [41]:
df.describe()

,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Average_Salary_USD,Job_Growth_2030,Work_Hours_Per_Week,Performance_Score,Job_Satisfaction
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,12.383000,0.502910,0.601203,126641.746667,17.238333,44.773333,3.514643,3.026167
std,7.528958,0.261293,0.226674,55405.053057,16.230322,8.926469,0.873375,1.146361
min,0.000000,0.050000,0.200000,30221.000000,-10.000000,30.000000,2.000000,1.000000
25%,6.000000,0.280000,0.420000,77262.000000,3.000000,37.000000,2.760000,2.060000
50%,12.000000,0.500000,0.600000,127660.500000,17.000000,45.000000,3.540000,3.025000
75%,19.000000,0.730000,0.800000,174811.750000,31.000000,52.000000,4.270000,4.010000
max,25.000000,0.950000,0.990000,219998.000000,45.000000,60.000000,5.000000,5.000000

In [42]:
df.isnull().sum()

Employee_ID                0
Job_Title                  0
Industry                   0
Country                    0
Education_Level            0
Years_Experience           0
AI_Replacement_Risk        0
Future_Demand_Score        0
Remote_Work_Possibility    0
Average_Salary_USD         0
Required_Skills            0
Automation_Level           0
Job_Growth_2030            0
Work_Hours_Per_Week        0
Company_Size               0
AI_Tool_Usage              0
Performance_Score          0
Upskilling_Needed          0
Job_Satisfaction           0
Hiring_Trend_2026          0
dtype: int64

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Employee_ID              3000 non-null   object
 1   Job_Title                3000 non-null   object
 2   Industry                 3000 non-null   object
 3   Country                  3000 non-null   object
 4   Education_Level          3000 non-null   object
 5   Years_Experience         3000 non-null   int64
 6   AI_Replacement_Risk      3000 non-null   float64
 7   Future_Demand_Score      3000 non-null   float64
 8   Remote_Work_Possibility  3000 non-null   object
 9   Average_Salary_USD       3000 non-null   int64
 10  Required_Skills          3000 non-null   object
 11  Automation_Level         3000 non-null   object
 12  Job_Growth_2030          3000 non-null   int64
 13  Work_Hours_Per_Week      3000 non-null   int64
 14  Company_Size             3000 non-null   object
 15  AI_Tool_Usage            3000 non-null   object
 16  Performance_Score        3000 non-null   float64
 17  Upskilling_Needed        3000 non-null   object
 18  Job_Satisfaction         3000 non-null   float64
 19  Hiring_Trend_2026        3000 non-null   object
dtypes: float64(4), int64(4), object(12)
memory usage: 468.9+ KB

In [44]:
df.drop(columns=['Employee_ID','Required_Skills'],inplace=True)

In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [81]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num',StandardScaler(),['Years_Experience','AI_Replacement_Risk','Future_Demand_Score','Average_Salary_USD','Job_Growth_2030','Work_Hours_Per_Week','Performance_Score','Job_Satisfaction']),
        ('cat',OneHotEncoder(handle_unknown="ignore"),['Job_Title','Industry','Country','Education_Level','Remote_Work_Possibility','Company_Size','AI_Tool_Usage','Upskilling_Needed','Hiring_Trend_2026'])
    ]
)

model_pipeline = Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('model1',LogisticRegression())
    ]
)

In [82]:
X = df.drop(columns=['Automation_Level'])
y = df['Automation_Level']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [83]:
model_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Years_Experience',
                                                   'AI_Replacement_Risk',
                                                   'Future_Demand_Score',
                                                   'Average_Salary_USD',
                                                   'Job_Growth_2030',
                                                   'Work_Hours_Per_Week',
                                                   'Performance_Score',
                                                   'Job_Satisfaction']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Job_Title', 'Industry',
                                                   'Country', 'Education_Level',
                                                   'Remote_Work_Possibility',
                                                   'Company_Size',
                                                   'AI_Tool_Usage',
                                                   'Upskilling_Needed',
                                                   'Hiring_Trend_2026'])])),
                ('model1', LogisticRegression())])

In [84]:
y_pred = model_pipeline.predict(X_test)

In [85]:
print(accuracy_score(y_test,y_pred)*100)

32.83333333333333

In [86]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [88]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(n_estimators=500,
    max_depth=15,
    random_state=42)
}

for name, model in models.items():
    pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("classifier", model)
    ])

    pipeline.fit(X_train, y_train)
    print(name, pipeline.score(X_test, y_test))

Logistic Regression 0.3283333333333333
Decision Tree 0.36833333333333335
Random Forest 0.3433333333333333

In [69]:
df["Industry"].nunique()

10

In [70]:
df["Industry"].value_counts(normalize=True)

Industry
Energy            0.111667
Government        0.107667
Finance           0.103333
Manufacturing     0.101000
Education         0.100000
Transportation    0.097667
Technology        0.097000
Media             0.095667
Retail            0.095000
Healthcare        0.091000
Name: proportion, dtype: float64

In [71]:
print(X.columns)

Index(['Job_Title', 'Country', 'Education_Level', 'Years_Experience',
       'AI_Replacement_Risk', 'Future_Demand_Score', 'Remote_Work_Possibility',
       'Average_Salary_USD', 'Automation_Level', 'Job_Growth_2030',
       'Work_Hours_Per_Week', 'Company_Size', 'AI_Tool_Usage',
       'Performance_Score', 'Upskilling_Needed', 'Job_Satisfaction',
       'Hiring_Trend_2026'],
      dtype='object')

In [79]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score

dummy = DummyClassifier(strategy="most_frequent")

dummy.fit(X_train, y_train)

pred = dummy.predict(X_test)

print("Dummy Accuracy:", accuracy_score(y_test, pred))

Dummy Accuracy: 0.11166666666666666

In [80]:
print(df.groupby("Industry")[[
    "Average_Salary_USD",
    "Years_Experience",
    "AI_Replacement_Risk",
    "Future_Demand_Score"
]].mean())

                Average_Salary_USD  Years_Experience  AI_Replacement_Risk  \
Industry
Education            124409.966667         11.853333             0.496933
Energy               127261.164179         12.931343             0.499164
Finance              132016.529032         12.264516             0.530484
Government           120626.349845         12.176471             0.528793
Healthcare           125682.307692         12.655678             0.475238
Manufacturing        128614.168317         12.953795             0.495875
Media                129684.560976         12.073171             0.489547
Retail               121075.284211         12.031579             0.496316
Technology           127689.281787         12.474227             0.517423
Transportation       129411.112628         12.361775             0.493754

                Future_Demand_Score
Industry
Education                  0.598833
Energy                     0.595642
Finance                    0.610710
Government                 0.621115
Healthcare                 0.612930
Manufacturing              0.605314
Media                      0.589721
Retail                     0.597544
Technology                 0.593471
Transportation             0.585290