In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/vigneshpgd/indian-retail-sales-analytics-dataset/sales_data.csv

In [3]:
df = pd.read_csv('/kaggle/input/datasets/vigneshpgd/indian-retail-sales-analytics-dataset/sales_data.csv')

In [4]:
df.shape

(15000, 22)

In [5]:
df.describe()

,Quantity,Unit_Price_INR,Discount,Sales_INR,Discount_Amount_INR,Net_Sales_INR,Cost_INR,Profit_INR,Shipping_Days,Customer_Satisfaction
count,15000.000000,15000.00000,15000.000000,15000.000000,15000.00000,15000.000000,15000.000000,15000.000000,15000.000000,15000.00000
mean,3.991333,1347.45306,0.106630,5396.765599,578.66473,4818.100912,2960.555138,1818.571167,3.678133,3.54920
std,1.993370,973.90804,0.087742,5225.206681,863.70892,4700.051718,2919.123008,1821.210884,1.669228,0.73522
min,1.000000,150.00000,0.000000,150.000000,0.00000,119.780000,75.110000,39.230000,1.000000,1.00000
25%,2.000000,708.49000,0.050000,2033.355000,17.45500,1793.360000,1090.092500,663.167500,2.000000,3.00000
50%,4.000000,1092.60500,0.100000,3901.345000,298.30500,3462.510000,2110.155000,1279.100000,4.000000,4.00000
75%,6.000000,1692.42750,0.150000,6949.402500,745.05250,6230.482500,3812.557500,2334.192500,5.000000,4.00000
max,7.000000,18616.06000,0.300000,130312.420000,13031.24000,117281.180000,70176.380000,47104.800000,8.000000,5.00000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Order_ID               15000 non-null  object
 1   Order_Date             15000 non-null  object
 2   Customer_ID            15000 non-null  object
 3   Region                 15000 non-null  object
 4   City                   15000 non-null  object
 5   Segment                15000 non-null  object
 6   Channel                15000 non-null  object
 7   Category               15000 non-null  object
 8   Subcategory            15000 non-null  object
 9   Product_ID             15000 non-null  object
 10  Quantity               15000 non-null  int64
 11  Unit_Price_INR         15000 non-null  float64
 12  Discount               15000 non-null  float64
 13  Sales_INR              15000 non-null  float64
 14  Discount_Amount_INR    15000 non-null  float64
 15  Net_Sales_INR          15000 non-null  float64
 16  Cost_INR               15000 non-null  float64
 17  Profit_INR             15000 non-null  float64
 18  Shipping_Days          15000 non-null  int64
 19  Returned               15000 non-null  object
 20  Customer_Satisfaction  15000 non-null  int64
 21  Payment_Method         15000 non-null  object
dtypes: float64(7), int64(3), object(12)
memory usage: 2.5+ MB

In [7]:
df.drop(columns=['Order_ID','Customer_ID'],inplace=True)

In [8]:
df.columns

Index(['Order_Date', 'Region', 'City', 'Segment', 'Channel', 'Category',
       'Subcategory', 'Product_ID', 'Quantity', 'Unit_Price_INR', 'Discount',
       'Sales_INR', 'Discount_Amount_INR', 'Net_Sales_INR', 'Cost_INR',
       'Profit_INR', 'Shipping_Days', 'Returned', 'Customer_Satisfaction',
       'Payment_Method'],
      dtype='object')

In [9]:
df.drop(columns=['Order_Date','Order_Date','Shipping_Days','Discount','Quantity','Product_ID'],inplace=True)

In [10]:
df.head(10)

,Region,City,Segment,Channel,Category,Subcategory,Unit_Price_INR,Sales_INR,Discount_Amount_INR,Net_Sales_INR,Cost_INR,Profit_INR,Returned,Customer_Satisfaction,Payment_Method
0,West,Pune,Corporate,Online,Home & Kitchen,Appliances,327.15,654.30,0.00,654.30,387.43,266.87,No,4,Debit Card
1,West,Ahmedabad,Corporate,Online,Beauty,Personal Care,1711.99,1711.99,171.20,1540.79,874.52,666.27,No,3,UPI
2,South,Chennai,Consumer,Online,Home & Kitchen,Cookware,1180.95,5904.75,295.24,5609.51,3095.78,2513.74,No,3,Net Banking
3,Central,Raipur,Consumer,Online,Home & Kitchen,Decor,703.24,1406.48,210.97,1195.51,720.77,474.74,No,3,Net Banking
4,North,Chandigarh,Consumer,Online,Home & Kitchen,Decor,380.55,1522.20,228.33,1293.87,820.70,473.17,No,3,Credit Card
5,South,Bengaluru,Consumer,Retail Store,Office Supplies,Printers,887.06,4435.30,443.53,3991.77,2257.63,1734.14,No,3,Debit Card
6,West,Pune,Consumer,Online,Office Supplies,Pens,2275.38,2275.38,455.08,1820.30,1093.09,727.22,No,4,UPI
7,South,Hyderabad,Corporate,Online,Office Supplies,Printers,957.15,5742.90,574.29,5168.61,2778.77,2389.84,No,4,UPI
8,North,Jaipur,Corporate,Marketplace,Office Supplies,Printers,670.95,1341.90,402.57,939.33,526.04,413.29,No,3,Credit Card
9,Central,Nagpur,Small Business,Online,Office Supplies,Binders,2589.88,5179.76,258.99,4920.77,2644.47,2276.30,No,4,Credit Card

In [11]:
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

In [12]:
from sklearn.model_selection import train_test_split
X = df.drop(columns=['Channel'])
y = df['Channel']

In [13]:
cat_col = X.select_dtypes(include=["object","category"]).columns.tolist()
num_col = X.select_dtypes(include=['int64','float64']).columns.tolist()

In [14]:
preprocessor = ColumnTransformer(
    transformers=[
       ('cat',OneHotEncoder(handle_unknown="ignore",sparse_output=False),cat_col),
        ('num',StandardScaler(),num_col)
    ]
)
model_pipeline = Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('model1',RandomForestClassifier(n_estimators=500,
    max_depth=15,
    random_state=42))
    ]
)

In [15]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [16]:
model_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Region', 'City', 'Segment',
                                                   'Category', 'Subcategory',
                                                   'Returned',
                                                   'Payment_Method']),
                                                 ('num', StandardScaler(),
                                                  ['Unit_Price_INR',
                                                   'Sales_INR',
                                                   'Discount_Amount_INR',
                                                   'Net_Sales_INR', 'Cost_INR',
                                                   'Profit_INR',
                                                   'Customer_Satisfaction'])])),
                ('model1',
                 RandomForestClassifier(max_depth=15, n_estimators=500,
                                        random_state=42))])

In [17]:
y_pred = model_pipeline.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
print(accuracy_score(y_test,y_pred))

0.5723333333333334

In [26]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [27]:
models = {
    "random forest":RandomForestClassifier(n_estimators=500,max_depth=15,random_state=42),
    "Decision tree":DecisionTreeClassifier(),
    "SVC":SVC(kernel="rbf"),
    "naive":GaussianNB(),
    "k-neighbor":KNeighborsClassifier(n_neighbors=5)
}
for name,model in models.items():
    model_pipeline = Pipeline([
        ("preprocessor",preprocessor),
        ("model",model)
    ])
    model_pipeline.fit(X_train,y_train)
    y_pred = model_pipeline.predict(X_test)
    print(name, accuracy_score(y_test,y_pred))

random forest 0.5723333333333334
Decision tree 0.42966666666666664
SVC 0.574
naive 0.417
k-neighbor 0.4746666666666667

In [22]:
df.head()

,Region,City,Segment,Channel,Category,Subcategory,Unit_Price_INR,Sales_INR,Discount_Amount_INR,Net_Sales_INR,Cost_INR,Profit_INR,Returned,Customer_Satisfaction,Payment_Method
0,West,Pune,Corporate,Online,Home & Kitchen,Appliances,327.15,654.30,0.00,654.30,387.43,266.87,No,4,Debit Card
1,West,Ahmedabad,Corporate,Online,Beauty,Personal Care,1711.99,1711.99,171.20,1540.79,874.52,666.27,No,3,UPI
2,South,Chennai,Consumer,Online,Home & Kitchen,Cookware,1180.95,5904.75,295.24,5609.51,3095.78,2513.74,No,3,Net Banking
3,Central,Raipur,Consumer,Online,Home & Kitchen,Decor,703.24,1406.48,210.97,1195.51,720.77,474.74,No,3,Net Banking
4,North,Chandigarh,Consumer,Online,Home & Kitchen,Decor,380.55,1522.20,228.33,1293.87,820.70,473.17,No,3,Credit Card

In [25]:
df.drop(columns=['Unit_Price_INR','Sales_INR','Discount_Amount_INR','Net_Sales_INR','Cost_INR','Profit_INR'],inplace=True)

In [28]:
X = df.drop(columns=['Channel'])
y = df['Channel']

In [29]:
models = {
    "random forest":RandomForestClassifier(n_estimators=500,max_depth=15,random_state=42),
    "Decision tree":DecisionTreeClassifier(),
    "SVC":SVC(kernel="rbf"),
    "naive":GaussianNB(),
    "k-neighbor":KNeighborsClassifier(n_neighbors=5)
}
for name,model in models.items():
    model_pipeline = Pipeline([
        ("preprocessor",preprocessor),
        ("model",model)
    ])
    model_pipeline.fit(X_train,y_train)
    y_pred = model_pipeline.predict(X_test)
    print(name, accuracy_score(y_test,y_pred))

random forest 0.5723333333333334
Decision tree 0.427
SVC 0.574
naive 0.417
k-neighbor 0.4746666666666667